---
max_opts: 50000000
eval_episodes: 1
eval_threshold: ~
model_dir: "./border/examples/atari/model/dqn_road_runner"
opt_interval: 1
eval_interval: 50000
record_interval: 50000
save_interval: 5000000
