---
max_opts: 50000000
eval_episodes: 1
eval_threshold: ~
model_dir: "./border/examples/atari/model/dqn_hero_ddqn"
opt_interval: 1
eval_interval: 500000
record_interval: 50000
save_interval: 10000000
